services:
  
  neo4j:
    container_name: neo4j
    image: neo4j:4.4.17
#   volumes:
#     - db_neo4j_volume:/data
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    restart: always
    env_file: .env
    environment:
      - NEO4J_USER
      - NEO4J_PASSWORD

  postgres:
    container_name: postgres
    image: postgres:latest
#   volumes:
#     - db_postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
# volumes:
#   db_postgres_volume:
#   db_neo4j_volume:
  
